import React, { useState, useEffect } from 'react';
import api from '../../services/api';

export default function DocumentRegisterTab({ triggerAlert }) {
  const [registers, setRegisters] = useState([]);
  const [loading, setLoading] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');

  useEffect(() => { fetchRegisters(); }, []);

  const fetchRegisters = async () => {
    setLoading(true);
    try {
      const res = await api.get('/documents/register');
      setRegisters(res.data);
    } catch (err) {
      triggerAlert('error', 'Failed to fetch document register');
    } finally {
      setLoading(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const handleExportCSV = () => {
    const headers = ['Register ID', 'Document Number', 'Student Name', 'Roll Number', 'Document Type', 'Generated By', 'Date', 'Status'];
    const rows = registers.map(r => [
      r.registerId, r.documentNumber, r.studentName, r.rollNumber, r.documentType, r.generatedBy, new Date(r.date).toLocaleDateString(), r.status
    ]);
    const csvContent = "data:text/csv;charset=utf-8," + [headers.join(','), ...rows.map(e => e.join(','))].join('\n');
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `Document_Register_${Date.now()}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const filtered = registers.filter(r => 
    r.studentName?.toLowerCase().includes(searchTerm.toLowerCase()) || 
    r.rollNumber?.toLowerCase().includes(searchTerm.toLowerCase()) ||
    r.documentType?.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '20px' }} className="no-print">
        <input type="text" placeholder="Search by student, roll, or doc type..." value={searchTerm} onChange={e => setSearchTerm(e.target.value)} style={{ padding: '8px', width: '300px', border: '1px solid #ccc', borderRadius: '4px' }} />
        <div style={{ display: 'flex', gap: '10px' }}>
          <button className="secondary" onClick={fetchRegisters}>Refresh</button>
          <button className="secondary" onClick={handleExportCSV}>Export Excel</button>
          <button className="primary" onClick={handlePrint}>Print Register</button>
        </div>
      </div>

      <div className="table-container printable-area">
        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '13px' }}>
          <thead>
            <tr style={{ backgroundColor: '#005b8e', color: '#fff' }}>
              <th>Register ID</th>
              <th>Doc Number</th>
              <th>Student Name</th>
              <th>Roll Number</th>
              <th>Document Type</th>
              <th>Generated By</th>
              <th>Date</th>
              <th>Status</th>
              <th className="no-print">Action</th>
            </tr>
          </thead>
          <tbody>
            {loading ? <tr><td colSpan="9" style={{ textAlign: 'center' }}>Loading...</td></tr> : 
             filtered.length === 0 ? <tr><td colSpan="9" style={{ textAlign: 'center' }}>No records found.</td></tr> :
             filtered.map(r => (
              <tr key={r._id}>
                <td>{r.registerId}</td>
                <td>{r.documentNumber || '-'}</td>
                <td>{r.studentName}</td>
                <td>{r.rollNumber}</td>
                <td>{r.documentType}</td>
                <td>{r.generatedBy || 'System'}</td>
                <td>{new Date(r.date).toLocaleDateString()}</td>
                <td><span className="badge active">{r.status}</span></td>
                <td className="no-print">
                  <button className="small secondary" onClick={() => triggerAlert('success', 'PDF Download triggered (placeholder)')}>Download PDF</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
